---
abstract: 'Perl interface to Git repositories'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  File::Find: 0
  File::Path: 0
  Test::More: 0.88
  constant: 0
  overload: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Repository
requires:
  Carp: 0
  Config: 0
  Cwd: 0
  Exporter: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::Handle: 0
  Scalar::Util: 0
  System::Command: 1.103
  Test::Builder: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Git-Repository
  repository: http://github.com/book/Git-Repository.git
version: 1.310
