---
abstract: 'Perl interface to the Amazon Elastic Compute Cloud (EC2)'
author:
  - 'Jeff Kim <cpan@chosec.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-EC2
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Digest::SHA: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Moose: 0.38
  POSIX: 0
  Params::Validate: 0
  URI: 0
  URI::Escape: 0
  XML::Simple: 2.18
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/mrallen1/net-amazon-ec2
version: 0.24
