---
abstract: 'Object for running system commands'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  Data::Dumper: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: System-Command
requires:
  Carp: 0
  Config: 0
  Cwd: 0
  Fcntl: 0
  IO::Handle: 0
  IPC::Run: 0
  List::Util: 0
  POSIX: 0
  Scalar::Util: 0
  Symbol: 0
  constant: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=System-Command
  repository: http://github.com/book/System-Command.git
version: 1.107
